<a href="https://colab.research.google.com/github/ElSangour/dataPreprocessing/blob/dev/dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**


In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the Dataset**

In [35]:
dataset=pd.read_csv('/dataSet.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [36]:
print(x)

[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 nan]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' nan 75000.0]]


In [37]:
print(y)

['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes']


**Handling Missing Data**


In [38]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)


[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 81918.3]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' 35.8 75000.0]]


**Encoding Categorical Data**

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 0.0 40.0 98479.0]
 [1.0 0.0 0.0 1.0 3.0 88582.0]
 [1.0 0.0 1.0 0.0 28.0 81129.0]
 [0.0 1.0 0.0 0.0 49.0 81918.3]
 [1.0 0.0 0.0 1.0 6.0 83036.0]
 [1.0 0.0 1.0 0.0 58.0 98158.0]
 [0.0 1.0 0.0 0.0 57.0 90484.0]
 [1.0 0.0 0.0 1.0 13.0 70478.0]
 [1.0 0.0 1.0 0.0 45.0 64905.0]
 [0.0 1.0 0.0 0.0 59.0 68932.0]
 [1.0 0.0 1.0 0.0 35.8 75000.0]]


In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 0 1 1 1 1 0 0 1 1]


**Splitting dataset into training and test set**

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print('x vector for training : \n')
print(x_train)
print('---------------------------------\n')
print('x vector for testing :\n')
print(x_test)
print('---------------------------------\n')
print('\ny vector for training : \n')
print(y_train)
print('\ny vector for testing : \n')
print(y_test)

x vector for training : 

[[0.0 1.0 0.0 0.0 59.0 68932.0]
 [1.0 0.0 0.0 1.0 3.0 88582.0]
 [0.0 1.0 0.0 0.0 57.0 90484.0]
 [0.0 1.0 0.0 0.0 40.0 98479.0]
 [1.0 0.0 0.0 1.0 13.0 70478.0]
 [1.0 0.0 1.0 0.0 35.8 75000.0]
 [1.0 0.0 1.0 0.0 45.0 64905.0]
 [1.0 0.0 1.0 0.0 58.0 98158.0]]
---------------------------------

x vector for testing :

[[1.0 0.0 1.0 0.0 28.0 81129.0]
 [0.0 1.0 0.0 0.0 49.0 81918.3]
 [1.0 0.0 0.0 1.0 6.0 83036.0]]
---------------------------------


y vector for training : 

[1 0 1 0 0 1 0 1]

y vector for testing : 

[0 1 1]


**Feature Scaling**

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.fit_transform(x_test[:,3:])


In [52]:
print(x_train)

[[0.0 1.0 0.0 -0.5773502691896258 1.0229513746475918 -1.0184167823626513]
 [1.0 0.0 0.0 1.7320508075688774 -1.8199904109735072 0.5274699153392933]
 [0.0 1.0 0.0 -0.5773502691896258 0.9214177394468384 0.67710230714739]
 [0.0 1.0 0.0 -0.5773502691896258 0.0583818402404333 1.3060775818612347]
 [1.0 0.0 0.0 1.7320508075688774 -1.3123222349697394 -0.8967912945943457]
 [1.0 0.0 1.0 -0.5773502691896258 -0.15483879368114928
  -0.5410406764259897]
 [1.0 0.0 1.0 -0.5773502691896258 0.31221592824231714 -1.3352252165430958]
 [1.0 0.0 1.0 -0.5773502691896258 0.9721845570472151 1.2808241655781647]]


In [53]:
print(x_test)

[[1.0 0.0 1.0 -0.7071067811865476 0.01898658122893107 -1.1487774293584592]
 [0.0 1.0 0.0 -0.7071067811865476 1.215141198651588 -0.13991711152368463]
 [1.0 0.0 0.0 1.4142135623730951 -1.2341277798805192 1.2886945408821437]]
