<a href="https://colab.research.google.com/github/ElSangour/dataPreprocessing/blob/dev/dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**


In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the Dataset**

In [35]:
dataset=pd.read_csv('/dataSet.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [36]:
print(x)

[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 nan]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' nan 75000.0]]


In [37]:
print(y)

['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes']


**Handling Missing Data**


In [38]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)


[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 81918.3]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' 35.8 75000.0]]


**Encoding Categorical Data**

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 40.0 98479.0]
 [0.0 0.0 1.0 3.0 88582.0]
 [0.0 1.0 0.0 28.0 81129.0]
 [1.0 0.0 0.0 49.0 81918.3]
 [0.0 0.0 1.0 6.0 83036.0]
 [0.0 1.0 0.0 58.0 98158.0]
 [1.0 0.0 0.0 57.0 90484.0]
 [0.0 0.0 1.0 13.0 70478.0]
 [0.0 1.0 0.0 45.0 64905.0]
 [1.0 0.0 0.0 59.0 68932.0]
 [0.0 1.0 0.0 35.8 75000.0]]


In [41]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 0 1 1 1 1 0 0 1 1]
