<a href="https://colab.research.google.com/github/ElSangour/dataPreprocessing/blob/dev/dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the libraries**


In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the Dataset**

In [35]:
dataset=pd.read_csv('/dataSet.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [36]:
print(x)

[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 nan]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' nan 75000.0]]


In [37]:
print(y)

['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes']


**Handling Missing Data**


In [38]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)


[['France' 40.0 98479.0]
 ['Spain' 3.0 88582.0]
 ['Germany' 28.0 81129.0]
 ['France' 49.0 81918.3]
 ['Spain' 6.0 83036.0]
 ['Germany' 58.0 98158.0]
 ['France' 57.0 90484.0]
 ['Spain' 13.0 70478.0]
 ['Germany' 45.0 64905.0]
 ['France' 59.0 68932.0]
 ['Germany' 35.8 75000.0]]


**Encoding Categorical Data**

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 0.0 40.0 98479.0]
 [1.0 0.0 0.0 1.0 3.0 88582.0]
 [1.0 0.0 1.0 0.0 28.0 81129.0]
 [0.0 1.0 0.0 0.0 49.0 81918.3]
 [1.0 0.0 0.0 1.0 6.0 83036.0]
 [1.0 0.0 1.0 0.0 58.0 98158.0]
 [0.0 1.0 0.0 0.0 57.0 90484.0]
 [1.0 0.0 0.0 1.0 13.0 70478.0]
 [1.0 0.0 1.0 0.0 45.0 64905.0]
 [0.0 1.0 0.0 0.0 59.0 68932.0]
 [1.0 0.0 1.0 0.0 35.8 75000.0]]


In [47]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 0 1 1 1 1 0 0 1 1]


**Splitting Dataset into Training set and Test set**

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0.0 1.0 0.0 0.0 40.0 98479.0]
 [0.0 1.0 0.0 0.0 49.0 81918.3]
 [1.0 0.0 0.0 1.0 3.0 88582.0]
 [0.0 1.0 0.0 0.0 57.0 90484.0]
 [1.0 0.0 1.0 0.0 58.0 98158.0]
 [1.0 0.0 0.0 1.0 6.0 83036.0]
 [1.0 0.0 1.0 0.0 35.8 75000.0]
 [1.0 0.0 1.0 0.0 45.0 64905.0]]
[0 1 0 1 1 1 1 0]
[[1.0 0.0 0.0 1.0 13.0 70478.0]
 [0.0 1.0 0.0 0.0 59.0 68932.0]
 [1.0 0.0 1.0 0.0 28.0 81129.0]]
[0 1 0]


**Feature Scaling**

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])
print(x_train)
print(x_test)

[[ 0.          1.          0.          0.         -0.51440498  1.43729268]
 [ 0.          1.          0.          0.          0.22992104  0.0115043 ]
 [ 1.          0.          0.          1.         -1.96523008  0.60492479]
 [ 0.          1.          0.          0.          0.87194693  0.28262032]
 [ 1.          0.          1.          0.          1.54227657  1.41036909]
 [ 1.          0.          0.          1.         -1.82691879  0.10041797]
 [ 1.          0.          1.          0.         -0.68656862 -0.80799495]
 [ 1.          0.          1.          0.          0.34897893 -2.03913352]]
[[ 1.          0.          0.          1.         -1.33569453 -1.53167521]
 [ 0.          1.          0.          0.          1.05137811 -1.67959034]
 [ 1.          0.          1.          0.         -0.61677655  0.05466777]]
